<a href="https://colab.research.google.com/github/abhinav101910/datascience/blob/main/program1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


import numpy as np

array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

array_with_range = np.arange(10)
print("Array with range:", array_with_range)

zeros_array = np.zeros((3, 3))
print("Array of zeros:\n", zeros_array)

ones_array = np.ones((2, 5))
print("Array of ones:\n", ones_array)



Array from list: [1 2 3 4 5]
Array with range: [0 1 2 3 4 5 6 7 8 9]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add_result = np.add(a, b)
print("Addition:", add_result)

sub_result = np.subtract(a, b)
print("Subtraction:", sub_result)

mul_result = np.multiply(a, b)
print("Multiplication:", mul_result)

div_result = np.divide(a, b)
print("Division:", div_result)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [3]:
import numpy as np
two_dimensional_array = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]])
excluding_first_row = two_dimensional_array[1:]
excluding_last_column = two_dimensional_array[:, :-1]
column_1_2_in_row_2_3 = two_dimensional_array[1:3, 0:2]
column_2_3 = two_dimensional_array[:, 1:3]
elements_2_3_in_first_row = two_dimensional_array[0, 1:3]
descending_order = two_dimensional_array.ravel()[::-1][4:11]
print("Original 2D array:\n", two_dimensional_array)
print("Elements excluding the first row:\n", excluding_first_row)
print("Elements excluding the last column:\n", excluding_last_column)
print("Elements of the 1st and 2nd column in the 2nd and 3rd row:\n",
column_1_2_in_row_2_3)
print("Elements of the 2nd and 3rd column:\n", column_2_3)
print("2nd and 3rd element of the 1st row:\n", elements_2_3_in_first_row)
print("Elements from indices 4 to 10 in descending order:\n", descending_order)

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Elements excluding the first row:
 [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Elements excluding the last column:
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Elements of the 1st and 2nd column in the 2nd and 3rd row:
 [[ 5  6]
 [ 9 10]]
Elements of the 2nd and 3rd column:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
2nd and 3rd element of the 1st row:
 [2 3]
Elements from indices 4 to 10 in descending order:
 [12 11 10  9  8  7  6]


In [4]:
import numpy as np
A = np.array([[2, 1,-2],[3,0,1],[1,1,-1]])
b = np.array([-3,5,-2])
X = np.linalg.solve(A, b)
print("Matrix A:")
print(A)
print("Vector b:")
print(b)
print("Solution for X:")
print(X)

Matrix A:
[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]
Vector b:
[-3  5 -2]
Solution for X:
[ 1. -1.  2.]
