<a href="https://colab.research.google.com/github/abhinav101910/datascience/blob/main/program1.4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", array_2d)

element = array_2d[1, 2]
print("Element at (1, 2):", element)

subarray = array_2d[1:3, 0:2]
print("Sliced subarray:\n", subarray)

column = array_2d[:, 1]
print("Column 1:", column)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 2): 6
Sliced subarray:
 [[4 5]
 [7 8]]
Column 1: [2 5 8]
